# Generated by Django 4.1.4 on 2023-01-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_clothes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClotheBookRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('in_favorites', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField()),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
