# Generated by Django 4.1.4 on 2023-01-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userclothebookrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothebookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ужасно!'), (2, 'Плохо!'), (3, 'Неплохо!'), (4, 'Отлично!'), (5, 'Я безумно доволен покупкой!')]),
        ),
    ]
