# Generated by Django 4.1.4 on 2023-01-18 21:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_alter_userclothebookrelation_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserClotheBookRelation',
            new_name='UserClotheRelation',
        ),
    ]
