# Generated by Django 4.1.4 on 2023-02-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_clothes_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='buyer',
        ),
        migrations.AddField(
            model_name='clothes',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
